// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYFpc3ViRn9MguRREweXurT1GWjdCuD1E',
    appId: '1:865160433178:web:7a37787ead69eb78d94ba3',
    messagingSenderId: '865160433178',
    projectId: 'fir-login-trial-e40d8',
    authDomain: 'fir-login-trial-e40d8.firebaseapp.com',
    databaseURL: 'https://fir-login-trial-e40d8-default-rtdb.firebaseio.com',
    storageBucket: 'fir-login-trial-e40d8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAqRNNvwf3qRMophbx1jRqXu9GXUrd5vM',
    appId: '1:865160433178:android:1d91334aca2ead01d94ba3',
    messagingSenderId: '865160433178',
    projectId: 'fir-login-trial-e40d8',
    databaseURL: 'https://fir-login-trial-e40d8-default-rtdb.firebaseio.com',
    storageBucket: 'fir-login-trial-e40d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6J9UOLGY-2EM5iFDhSCH86RQcUKJ8u4c',
    appId: '1:865160433178:ios:f6e9ba951fe6d40fd94ba3',
    messagingSenderId: '865160433178',
    projectId: 'fir-login-trial-e40d8',
    databaseURL: 'https://fir-login-trial-e40d8-default-rtdb.firebaseio.com',
    storageBucket: 'fir-login-trial-e40d8.appspot.com',
    iosClientId: '865160433178-h7o8b12a8g95qmtb9ug6fpst3gn31n0t.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6J9UOLGY-2EM5iFDhSCH86RQcUKJ8u4c',
    appId: '1:865160433178:ios:f6e9ba951fe6d40fd94ba3',
    messagingSenderId: '865160433178',
    projectId: 'fir-login-trial-e40d8',
    databaseURL: 'https://fir-login-trial-e40d8-default-rtdb.firebaseio.com',
    storageBucket: 'fir-login-trial-e40d8.appspot.com',
    iosClientId: '865160433178-h7o8b12a8g95qmtb9ug6fpst3gn31n0t.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );
}
